// Bake the MFF expected-completion (xComp) table for CPOE.
//
// First-principles: CPOE = Completion Percentage Over Expected. It measures
// QB ACCURACY ABOVE BASELINE — how much the QB beats (or fails) the
// expected completion rate for a given throw difficulty. So the expected
// model MUST BE SKILL-FREE: it depends on throw difficulty (depth,
// pressure, maybe weather) but NOT on the QB. Otherwise CPOE collapses
// to ~0 for everyone — you'd be subtracting the QB's own expected from
// his actual.
//
// Method: walk every pass attempt (complete + incomplete) in a 2-season
// round-robin. Bucket by (targetDepth_bucket, pressure_bucket). Record
// empirical completion rate per cell. Skill-free by construction.
//
// Buckets:
//   depth:    0=short(≤5)  1=medium(6-15)  2=deep(16+)
//   pressure: 0=clean(<0.3)  1=pressured(0.3-1.0)  2=heavy(≥1.0)
//   → 9 cells; sample size ≥ 1000 per cell in a 2-season run.
//
// Output: /tmp/mff_xcomp_baked.js — paste into play-franchise-stats.js.
const fs = require("fs"), path = require("path");
const files = ["play-data.js","play-player.js","play-render.js","play-sim.js","play-motion.js","play-engine.js"];
function stripUiInit(c,f){return f!=="play-render.js"?c:c.replace(/^buildOptions\([^)]*\);\s*$/gm,"//x").replace(/^setupPreview\([^)]*\);\s*$/gm,"//x");}
const shim = `var _stub=new Proxy(function(){},{get(t,k){if(k==="style"||k==="classList"||k==="dataset")return _stub;if(k==="length")return 0;if(k===Symbol.iterator)return function*(){};return _stub;},set(){return true;},apply(){return _stub;},construct(){return _stub;}});
var document={createElement:()=>_stub,getElementById:()=>_stub,querySelector:()=>_stub,querySelectorAll:()=>[],addEventListener:()=>{},body:_stub,documentElement:_stub};
var window=(typeof globalThis!=="undefined"?globalThis:this);window.addEventListener=()=>{};
if(typeof performance==="undefined")var performance={now:()=>Date.now()};var requestAnimationFrame=()=>0;
var localStorage={getItem:()=>null,setItem:()=>{},removeItem:()=>{}};`;
const driver = `;(function(){
  const SEASONS = Number(process.argv[2] || 2);
  function depthB(td) { if (td <= 5) return 0; if (td <= 15) return 1; return 2; }
  function pressB(pr) { const a = Math.abs(pr); if (a < 0.3) return 0; if (a < 1.0) return 1; return 2; }
  const ros = {}; for (const t of TEAMS) ros[t.id] = genRoster(getPlaybook(t),{},null);
  const acc = {};   // key → {comp:0, att:0}
  const totals = { comp: 0, att: 0 };
  for (let s = 0; s < SEASONS; s++) {
    if (s > 0) for (const t of TEAMS) ros[t.id] = genRoster(getPlaybook(t),{},null);
    for (let i = 0; i < TEAMS.length; i++) for (let j = i+1; j < TEAMS.length; j++) {
      const sim = new GameSimulator(TEAMS[i], TEAMS[j], ros[TEAMS[i].id], ros[TEAMS[j].id]);
      sim.simulate();
      for (const p of sim.plays) {
        // Only pass attempts (not sacks/INTs — those aren't accuracy
        // events). Underthrown completes/incompletes ARE accuracy events.
        if (p.kind !== "complete" && p.kind !== "incomplete") continue;
        if (typeof p.targetDepth !== "number") continue;
        const db = depthB(p.targetDepth);
        const pb = pressB(p.pressure || 0);
        const k = db + "|" + pb;
        if (!acc[k]) acc[k] = { comp: 0, att: 0 };
        acc[k].att++;
        totals.att++;
        if (p.kind === "complete") { acc[k].comp++; totals.comp++; }
      }
    }
  }
  const XCOMP = {};
  for (const k of Object.keys(acc).sort()) {
    const e = acc[k];
    XCOMP[k] = +(e.comp / e.att).toFixed(4);
  }
  console.error("Bake: " + totals.att + " pass attempts in " + SEASONS + " seasons (" + totals.comp + " complete, " + (100*totals.comp/totals.att).toFixed(1) + "%).");
  console.error("xComp by (depth, pressure):");
  const dLabels = ["short(≤5)", "mid(6-15)", "deep(16+)"];
  const pLabels = ["clean", "pressure", "heavy"];
  for (let d = 0; d < 3; d++) {
    for (let p = 0; p < 3; p++) {
      const k = d + "|" + p, e = acc[k];
      if (e) console.error("  " + dLabels[d].padEnd(11) + " × " + pLabels[p].padEnd(9) + " : " + (100*e.comp/e.att).toFixed(1) + "%  (n=" + e.att + ")");
    }
  }
  const out = [];
  out.push("// Baked xComp table — generated by _mff_bake_xcomp.js (do not edit).");
  out.push("// Method: empirical completion rate per (depth_bucket, pressure_bucket).");
  out.push("//   depth:    0=short(≤5)  1=mid(6-15)  2=deep(16+)");
  out.push("//   pressure: 0=clean(<0.3)  1=pressure(0.3-1.0)  2=heavy(≥1.0)");
  out.push("// Skill-free by construction — does NOT depend on QB attributes,");
  out.push("// so CPOE = (actual_complete - xComp) measures QB accuracy above baseline.");
  out.push("const _MFF_XCOMP_TABLE = " + JSON.stringify(XCOMP) + ";");
  globalThis.__mffXcompOut = out.join("\\n");
})();`;
let code = shim + "\n";
for (const f of files) { let c = fs.readFileSync(path.join(__dirname, f), "utf8"); c = stripUiInit(c, f); code += "\n" + c + "\n"; }
code += driver;
require("vm").runInThisContext(code, { filename: "_mff_bake_xcomp_bundle.js" });
fs.writeFileSync("/tmp/mff_xcomp_baked.js", globalThis.__mffXcompOut);
console.error("Wrote /tmp/mff_xcomp_baked.js (" + globalThis.__mffXcompOut.length + " bytes).");
