// artifact.js — the canonical match-INPUTS artifact + its SHA-256 hash. Single
// source of truth shared by the server (h2h-server.js), the probe (h2h-probe.js)
// and the standalone verifier (verify-artifact.js) so the inputs hash can never
// drift between producer and verifier.
//
// `hash` (this) binds the INPUTS {seed, rosters, tape, ...}; `resultHash`
// (result-hash.js) binds the OUTCOME. Together they are the settlement pair a
// ProofSettlement runner posts and a challenger disputes. `math` declares which
// transcendental mode reproduces the result bit-for-bit (see GC_PORTABLE_MATH).
"use strict";
const crypto = require("crypto");

// Canonical inputs object — FIXED key order (the hash is order-sensitive). v2
// added `math`. Accepts a match `m` or a served artifact (same field names).
function artifactInputs(a) {
  return {
    v: 2,
    seed: a.seed,
    homeTeamId: a.homeTeamId,
    awayTeamId: a.awayTeamId,
    settings: a.settings,
    math: a.math,
    rosters: a.rosters,
    tape: a.tape,
  };
}

function artifactInputsHash(a) {
  return crypto.createHash("sha256").update(JSON.stringify(artifactInputs(a))).digest("hex");
}

// ── per-call SIGNATURE canon (shared by h2h-server, verify-artifact, and the
// league's solo-accept ingest so producer and verifiers can never drift) ────
// message: hh-call|matchId|seq|by|JSON(normalized call); by = the signer lane
// ("home"/"away" seat key, or "server" for clock/settings-generated entries).
function sigMessage(matchId, seq, by, call) {
  const norm = (call === "auto" || call == null) ? null : call;
  return Buffer.from(`hh-call|${matchId}|${seq}|${by}|${JSON.stringify(norm)}`);
}
function verifyCallSig(pubJwk, msg, sigB64) {
  try {
    const key = crypto.createPublicKey({ key: pubJwk, format: "jwk" });
    return crypto.verify("sha256", msg, { key, dsaEncoding: "ieee-p1363" }, Buffer.from(String(sigB64), "base64"));
  } catch (_) { return false; }
}
// Full artifact signature pass: sigs[i] attests tape[i]. Unsigned = a visible
// coverage gap (legacy seat), invalid = forged/tampered. A FULLY-covered
// artifact (unsigned === 0, invalid === 0) is self-proving: every entry was
// authorized by its seat's key or generated by the authority.
function verifySignatures(art) {
  const out = { present: false, valid: 0, invalid: 0, unsigned: 0,
    byHome: 0, byAway: 0, byServer: 0, invalidAt: [] };
  if (!Array.isArray(art.sigs) || !art.keys || !Array.isArray(art.tape)) return out;
  out.present = true;
  for (let i = 0; i < art.tape.length; i++) {
    const rec = art.sigs[i];
    if (!rec || !rec.sig) { out.unsigned++; continue; }
    const ok = !!art.keys[rec.by]
      && verifyCallSig(art.keys[rec.by], sigMessage(art.id, i, rec.by, art.tape[i]), rec.sig);
    if (ok) {
      out.valid++;
      if (rec.by === "home") out.byHome++;
      else if (rec.by === "away") out.byAway++;
      else out.byServer++;
    } else { out.invalid++; out.invalidAt.push(i); }
  }
  return out;
}

module.exports = { artifactInputs, artifactInputsHash, sigMessage, verifyCallSig, verifySignatures };
